RL_DEFAULTS = {
    "ppo": {
        "name": "ppo_controller",
        "algorithm_name": "PPO",
        "policy": "MlpPolicy",
        "learning_rate": 3e-4,
        "n_steps": 2048,
        "batch_size": 64,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
    "sac": {
        "name": "sac_controller",
        "algorithm_name": "SAC",
        "policy": "MlpPolicy",
        "learning_rate": 3e-4,
        "buffer_size": 100000,
        "batch_size": 256,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
    "td3": {
        "name": "td3_controller",
        "algorithm_name": "TD3",
        "policy": "MlpPolicy",
        "learning_rate": 3e-4,
        "buffer_size": 100000,
        "batch_size": 256,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
    "a2c": {
        "name": "a2c_controller",
        "algorithm_name": "A2C",
        "policy": "MlpPolicy",
        "learning_rate": 7e-4,
        "n_steps": 5,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
    "ddpg": {
        "name": "ddpg_controller",
        "algorithm_name": "DDPG",
        "policy": "MlpPolicy",
        "learning_rate": 1e-3,
        "buffer_size": 100000,
        "batch_size": 256,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
    "dqn": {
        "name": "dqn_controller",
        "algorithm_name": "DQN",
        "policy": "MlpPolicy",
        "learning_rate": 1e-4,
        "buffer_size": 100000,
        "batch_size": 32,
        "gamma": 0.99,
        "device": "cpu",
        "verbose": 1,
    },
}